language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: amCOXgcgvo/ZmulJEaVF6LTL1cwFEu3oBMSlWhm9KTsq7Wf9weT0cRUhPcNO5XRPJSjg+Y6Qt6ncyq4FM6s/48k8Qgzxludxqfs3lV1YGleJrzbcHmer4227MY09nmCH3mlaKyrfZDhb1BbNH2RnqAz7IuH02zjSIyzbs4oRvTNDXUvvcMHkXUG31vF3k/R1iJ7TP7sEuXXQWnX33Gz3r7gR8ecv+DtNu+c8fzuC2KRJa5OeuEcdzNtvO2WcqBusQl8SjBTARV+A8FCsa1rnqSNbzudNiIuLaaAJNRZ3G9Sc6wtiLKHH9vXnd1UntLBLn8SYhkgIHJZUaWdZt5v9BMO2rjRvtIPX9+EcL6LUlo9moQflhcfJyDjRdToIAa9JnmaKx/z0EzK8GiTn65x2zLzpNvNrSvF0PR4TaPeL+TD/v5P5hVmjmDwo1mJX7yZfE2so6arhJbaOdF2I/I+2M7R49OJvAN8NciPxy/nPe6wIJ14Dq94t350IzmfeBYf1zt2i8cnQc1f+YHmDpxAZW7XVVcWgTFcsNG7KREyO+DMMnRMYHf6mhvDayFR4rMfxR18Wa6BiOBf9fHwHsFrbaOpeeW8p1Ka/ql2mDV11vtL1VX5GPa80odntHje3ZbI9oI+m9b19Pcp1Kc4C9yxg5zCXRUSTFniMvLrRFD8eac4=
  app: https://git.heroku.com/quiet-gorge-178790.git
  on:
    repo: RyanOkamuro/node-restaurants-app-mongoose
