language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key: ba5782a9-e724-4ef2-b066-989ee11c7a0d
    secure: UYa0YEaq4V3qIjXcj38EidKc8aSsQKD15WMwSLvyzSMtAxvPY0jjUweq7PnYUFCZE59qRbIrCAixD3MDoXH0b7ART2ApoxV90v0XPrX8kObN2qHacOG2/S+bJ6dZUUE6mTu2pRiSmxELfqeqJUXntSUe2LNeex+t5qoLRPP+RgWifvDs4EfRBxVjXUoSbJocpcqfLcT4sKOmHgh9JRFmMgL1bmuuZhPrLK+xWHLxwCLOu0qwAdtidz1K8pxdaUY8/2MM6KwZF+UtIbgVVnMAricygHM2pHcVO8M6Iy8OJL/31Mz2AitsR8TwAk290PxQn/X7d08/W1ApCmhhHin8pNNtGhOi+7+3aPySY+tiUgFrH8amACzf6Lbg6F2b2YXur+PUL+20reXgTTTf2nLC8t0dGpmcd/WdwnwwdrQO5mVeNfiRXXZspI55ONa6jcjN3V6jEhUvLSF4BlKZT8pemraYlrWOTpMuPMUbb0pyhICNoOhKg/bWbzLdCfFSVpLchyjXxqXQAYueRI/eGCQWsCpWxabukYaq+oEf5Y39+fJ7Jg7SJHAvAc5UviySkoPRnwErjg8pqSGT/Ukt/mskgAvieKUJT0rpe207PAnTRtMZ6v4gCAa1DLlABMK65CRz9r2B6c6N8Qt70GJVjPsPPTLAfEatJBJWPqjSJXP/tIA=
  app: https://stormy-scrubland-47363.herokuapp.com/
  on:
    repo: RyanOkamuro/node-restaurants-app-mongoose
