language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: PCZJ4kpoH8cLr9Z1X9trS0Hgp3h87bYm1cdmA1PhKLTSpYISVJ5VHhabQ6M/ImyUfl2uwKZ5b9fsK74Tybbljbzw2IwJw8p9Tt2AFlySyYcjzGZT0fFKQcNH0ftPRgV2X3HhdcLpoYv+uG+7GleG5RBDyf8vwvXBqZAgG7z8IK9wiUQtdE1j1vkI73zNq5NFHJaVkqzIW/gAx3ix37aFrTSt6teTI1bSUqvqxLkmfOZaosRgcGQ/E2McCpI1o8fXdWpZf9anogsu39Ew7KT2gZvi+05JQncoUEpANyxA9CZ+wa4CwX/9Vbb0mbU3qa/2ZVqY3vmnOWhZGOJjwhmn7oziU8smuOMMBa3rOKhFZLjzFUrgR6NcJIhgPoD93EdOBpd7G0tYCDD30OPRcUy2wnpMT+sVt6k0TpUm6iJ690us9kdQQej7ozpLmJSmLfKMzgS24LD5WJ9cKFaTVJBuAt2FDB7F3SzRo2I2vV62VK15SF3VhpZLD6FCeMSFID8/nEeRX63upae7qtYA6SX/ibZ3tzfkTVSWnTOybXy0w3ieVIVJcXNXrJC1Dv+6Dw8loTACiaLIjpnpDQn7hdV1F4rzVR3fffEkYkWusVq6wvmUV97dmgtvW4T8T24mv5efgeRKUXEUoreoPcsespvbbdKKmbDzEKeFrkbTnMw6oHM=
  app: shielded-everglades-62045
  on:
    repo: RyanOkamuro/node-restaurants-app-mongoose
